### ISSUE TITLE
Bugs related to app generator page

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1045]
**App generator issues**
I invite all to discuss the issues related to the app generator page.

**Generate app button**

- Enabled if email is empty
- Remains disabled if zip is uploaded before entering the email.
- Colour of alert shown if incorrect email is entered should be changed to red.

**Cancel generation**

- When user clicks X while app is generating, the generation process must stop
- Disable all the buttons, radio buttons while app is generating
- Hide logs, status text, progress bar when user cancels

**Other**

- Hide progress bar if the app has been generated.
- Reset app generator if source is changed.
- Increase spacing between buttons.

**Comment by aayusharora** [comment]
`Generate app button
Enabled if email is empty`
This is obvious that it should be disabled. Why enabled? @geekyd

**Comment by poush** [comment]
```Enabled if email is empty```
Don't see why it would be appropriate.

```Remains disabled if zip is uploaded before entering the email.```
Going with above point. You are trying to say to a user that till you do not enter anything or just email or both, you are good to go.

```Colour of alert shown if incorrect email is entered should be changed to red.```
Instead, I prefer the colour of input box borders to be updated. Changing colour of button with different states as well i.e, disabled and enabled makes confusing UI.

```Disable all the buttons, radio buttons while app is generating```
Good to go but there should be some better way. I will see what can I suggest here.

```Hide logs, status text, progress bar when user cancels```
I think logs should be archived of previous builds and should be accessible on that page to that user.

```Hide progress bar if the app has been generated.```
Yes, it can be but again I think we can do this in some better way as well instead of just hiding or maybe some animation on hiding.

**Comment by geekyd** [comment]
Sorry about the confusion 

Generate app button enabled if email is empty refers to the current behaviour.

It should be disabled, that's the fix.

**Comment by geekyd** [comment]
@poush Great suggestions. 😄

**Comment by sumedh123** [comment]
@geekyd Where is the cancel button to cancel the website generation process?

**Comment by geekyd** [comment]
@sumedh123 There is 'X' right next to the upload progress bar which can be used to cancel the generation of the webapp.

**Comment by sumedh123** [comment]
What if I use API endpoint? @geekyd

**Comment by geekyd** [comment]
We currently don't have a button for cancelling the generation using API generation. But it would be great to have it for generation using API endpoint.
