### ISSUE TITLE
Cannot generate app from API for FOSSASIA'17

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1050]
The following API link generates an error message: https://eventyay.com/api/v1/events/6?include=sessions,microlocations,tracks,speakers,sponsors

`INFO:Cleaning up the previously existing temporary folders
SUCCESS:Successfully cleaned up the temporary folders
INFO:Making the dist folder
SUCCESS:Dist directory made successfully
INFO:Copying Assets
SUCCESS:Assets were successfully copied
INFO:Cleaning dependencies folder created as a part of copying assets inside the appFolder
INFO:Reading the contents of the dependenices directory
INFO:All files of the folder have been copied
INFO:Now removing the dependenices folder
SUCCESS:Dependencies folder cleaned successfully
INFO:Copying Jsons
INFO:Fetching Jsons from the internet
INFO:Creating json folder insde the appPath directory
SUCCESS:All jsons have been successfully downloaded
SUCCESS:SASS file compiled successfully
SUCCESS:css file was written successfully
INFO:Extracting data from the uploaded jsons
ERROR:Invalid ZipKnow More
TypeError: speakers.map is not a function`

![screenshot from 2017-02-22 12-13-18](https://cloud.githubusercontent.com/assets/1583873/23197084/b8c92ca4-f8f8-11e6-8bc9-744986029c63.png)

**Comment by Princu7** [comment]
@mariobehling I am on it :)

**Comment by aayusharora** [comment]
@princu cool.

**Comment by aayusharora** [comment]
@princu, its urgent. Kindly ask if you need any help.

**Comment by Princu7** [comment]
@aayusharora Sure. If there are any issues, I will look out for guidance. Thank you so much :)

**Comment by Princu7** [comment]
@mariobehling @aayusharora Okay, there were some errors in the API section of the app due to which the event site was not being generated properly. Also, there are some sessions which don't have any detail containing information like start time, end time, short abstract etc. The app was also crashing because of it. Presently, I have ignored those sessions. How should we deal with them? Also, there are some issues with the sharp module which is used in the app for converting an image to a different resolution. Fortunately, it doesn't affect the app and it works fine in spite of all the errors.

Anyways, here is the Test Server
`https://peaceful-earth-19050.herokuapp.com`

API endpoint
`https://eventyay.com/api/v1/events/6`

**Comment by Princu7** [comment]
Off-topic
@aayusharora Feels great to see you there on the Speakers list. Hope you deliver an amazing talk. Best of luck :heart:

**Comment by mariobehling** [comment]
@Princu7 Which PR is it?

**Comment by Princu7** [comment]
@mariobehling I have just deployed the test server which corrects the errors in the official app. I haven't created the PR yet because of the above-outlined issues. Sorry. Should I also open a PR for it?

**Comment by mariobehling** [comment]
@Princu7 Same error message as before with: https://eventyay.com/api/v1/events/6?include=sessions,microlocations,tracks,speakers,sponsors

**Comment by Princu7** [comment]
@mariobehling Please try with the API endpoint `https://eventyay.com/api/v1/events/6`. It is currently configured with it.

**Comment by Princu7** [comment]
@aayusharora I guess this issue can be closed now :)
