### ISSUE TITLE
Deploy 2017 summit on each merged PR to event page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1054]
The event page of the 2017 summit is hosted at https://github.com/fossasia/2017.fossasia.org

Please add the schedule to the folder /app in the repository and deploy it on each merged PR using the API here: https://eventyay.com/api/v1/events/6?include=sessions,microlocations,tracks,speakers,sponsors

**Comment by Princu7** [comment]
I will do it as soon as the API endpoint problem is fixed :)

**Comment by Princu7** [comment]
@mariobehling @aayusharora We are presently deploying the FOSSASIA 16 sample on every PR merge against the development branch. Changing it to FOSSASIA 17 shouldn't be much difficult and should only require some changes in the code.

The issue is that all the event sites are generated in the folder named `dist` .  The generation and the deployment code has been written according to that. There is no folder named `app`. Doing it in the above mentioned manner would be convoluted and kinda unnecessary. Can't we follow the same workflow as before? Apart from being easier, it will also be less error-prone. Please guide. Thanks!!

**Comment by aayusharora** [comment]
@Princu7 No worries for that. I have updated the code to work with FOSSASIA 17, we will keep the dist/ folder for now to avoid any confusion. We just have to replace the it to FOSSASIA17 sample.

**Comment by aayusharora** [comment]
It is done now.
