### ISSUE TITLE
Generated zip shows download location on Amazon and has cryptic name

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1066]
The email the user gets after the app is generated from the API is very long and cryptic (e.g. bebdc3d2-7134-4fe5-8c42-aff86c5717b0FOSSASIA+Summit.zip) and the download location is an AWS link.

Expected: FOSSASIA_Summit.zip and link on deployment site.

**Comment by Princu7** [comment]
@mariobehling It is related to this issue #509 
We were aiming to make the download link unique and hence used the `node-uuid` module for generating cryptic hash which is guaranteed to be unique for many lifetimes.
 
With download link on deployment site, did you mean download link on Heroku? It is not possible since Heroku doesn't provide persistent storage and hence we had to upload the event zip to AWS S3 and give that download link in the email sent to the user.

**Comment by mariobehling** [comment]
@Princu7 There is a difference between a download link and the name of the download file. The download link should be unique. The download file should not be cryptic and stick to the name of the event.

![screenshot from 2017-03-02 22-42-19](https://cloud.githubusercontent.com/assets/1583873/23511888/b0473de4-ff99-11e6-8dd8-e163765bbd4b.png)

**Comment by Princu7** [comment]
@mariobehling Yes. The issue is that the download link of the uploaded AWS S3 Objects are of the form of  `https://mybucket.s3.amazonaws.com/myfilename`
So, we had to vary the name of the file to keep the download link consistent and unique. Will try to see if there is any other way for this.

**Comment by Princu7** [comment]
@mariobehling @aayusharora Ok I did it using an alternative way. Now a folder having a unique `uuid` name is being created for every upload and the generated event zip file is kept under that folder. The folder name is unique so there will be no overwriting of it. The event zip file will have its original name inside that folder and only this name will be displayed while downloading the file. Both the problem gets solved in this manner :)
