### ISSUE TITLE
Design issue of icons and speaker images

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1069]
There are a number of issues with the design, that were solved before and were changed (I do not see who changed it in which PR).

* [ ] Scroll over on social icons on speaker images makes the icons red. It should not make them red.
* [ ] Some pictures of speakers in tracks do not display properly
![screenshot from 2017-02-23 19-58-06](https://cloud.githubusercontent.com/assets/1583873/23258337/be118fa2-fa02-11e6-88b2-65a2ab5cbf90.png)

**Comment by CosmicCoder96** [comment]
@mariobehling I would like to work on this.

**Comment by geekyd** [comment]
@mariobehling Sir the pictures of speakers in tracks is not displayed properly due to lack `"session_type" = null` of the speaker which is in the data used from API.

Due to the missing attribute `name` in the `session_type` the track is missing the type of the session which present for other tracks.

**Comment by Princu7** [comment]
@geekyd Thank you so much for reporting the issue :) Yeah, some of the session have their session_type property set to null which is the cause of the error. I have open an issue regarding this on the open-event-orga-server. Thanks!!
