### ISSUE TITLE
Text Appending outside div 

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1077]
The tracks contain some overflow of content. Please check why the content is shown without even clicking on the div.
![wrong](https://cloud.githubusercontent.com/assets/12194719/23330349/ba414d20-fb71-11e6-896b-1137360af345.png)

**Comment by geekyd** [comment]
@aayusharora I will check it out.

**Comment by geekyd** [comment]
@aayusharora I have figured out what is happening. We are displaying `description` for every session of the track, which corresponds to the `long_abstract` from the json data.
We assume that long_abstract would be `null` but for some speakers both `long_abstract` and `short_abstract` is set. Due to the `description` for each session not being `null` is the cause of the issue.

**Comment by Princu7** [comment]
@aayusharora @geekyd This issue will be solved with #1061 :)

**Comment by geekyd** [comment]
@Princu7 Okay 👍 
Some speakers have both `long_abstract` and `short_abstract` set, so keep that in mind 😄
