### ISSUE TITLE
Show also end times of sessions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1104]
Originally we decided to only show start times of sessions, but after user feedback it seems better to also include the end time of sessions as people do not know how much "space time" is between sessions otherwise.

Therefore please implement to show session end times on all schedule, tracks, room pages.

![screenshot from 2017-03-02 00-41-35](https://cloud.githubusercontent.com/assets/1583873/23470395/3b2eae38-fee1-11e6-917b-da1b98d8cfdf.png)

**Comment by geekyd** [comment]
@mariobehling I will make the changes, asap. Should i place the end time next to start time?

**Comment by aayusharora** [comment]
@geekyd Please use the format startime - endtime

**Comment by geekyd** [comment]
@aayusharora Im'm on it :) Thanks

**Comment by geekyd** [comment]
@mariobehling @aayusharora The schedule page has all the events starting at same time grouped together, they might have different end time. Should we ungroup them and make the list?

Please guide. Thanks

**Comment by aayusharora** [comment]
Hey @geekyd I guess there is a bug here too, if you see the timings for the two events on `17 March` it stated them separately `00:00`. If they have been grouped according to start time, they must be grouped together in the time without repetition of the timings.
Now, what I suggest is to ungroup them because the grouping seems already buggy and then too state the end time, be sure to sort them according to timings, same as it is done now.

**Comment by mariobehling** [comment]
@geekyd Good point. Let's keep the schedule page as is for now and only change tracks and rooms page for the moment. Cheers.

**Comment by geekyd** [comment]
@mariobehling We have made changes to the schedule page please check http://fossasia.github.io/open-event-webapp/schedule.html

Please give your feedback
Thanks.
