### ISSUE TITLE
Background image as png and too large

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1122]
The header background image of start page is saved as a png and very large, e.g. the image of the FOSSASIA Summit is 1.8MB.

**Comment by geekyd** [comment]
@mariobehling I will scale it down and save it as JPEG

**Comment by geekyd** [comment]
@mariobehling @aayusharora We should convert all the pngs to jpg, as soon as we download them.
That would a good option, for reducing the image sizes, in the web-app

**Comment by Princu7** [comment]
@geekyd Yeah. I am already converting the speaker and sponsors images in png to jpeg. Issue #1123

**Comment by geekyd** [comment]
@Princu7 Excellent! That would be great. We should keep jpeg as standard.

**Comment by Princu7** [comment]
Yes. I did some of the prototype work and from that it seems like, it can save up a lot of the space used on the images :)

**Comment by aayusharora** [comment]
@Princu7 @geekyd I am also working on this, if you have already started please continue. But please replace the sharp module from `jimp`https://www.npmjs.com/package/jimp. This can help us a lot.

**Comment by Princu7** [comment]
@aayusharora Jimp seems to be a great library. Any particular reason over choosing this instead of sharp?  One advantage that I can think is that it is written entirely in Javascript and has no external dependencies. Sharp depends on some C++ libraries I Guess. But that feature also gives a speed boost to the sharp as it is able to quickly resize the images when compared to other libraries. Would love to hear you opinions. Thanks

**Comment by geekyd** [comment]
@Princu7 @aayusharora `Jimp` and `sharp` module are very similar, apart from being independent of externals , there is not much that separates these modules. I think we should stick to `sharp` it offers better performance.

**Comment by aayusharora** [comment]
@geekyd @princu7 I feel less developer support for sharp, most of the developers are not able to build app on Windows because of sharp external dependencies. 
Also as we are going to JPEG format, jimp can give a a better performance boost. 
I like if we can compare the performance results and than can decide which is suitable.
