### ISSUE TITLE
Rooms : Missing room names for search results

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1157]
The Search results for rooms page do not have the name of the room. This makes the nav-bar buggy for the searched results.
**Current behaviour** 

![screen shot 2017-03-11 at 1 24 02 pm](https://cloud.githubusercontent.com/assets/12807846/23821619/1f1cc002-065e-11e7-962c-b97e8767c597.png)

![screen shot 2017-03-11 at 1 24 24 pm](https://cloud.githubusercontent.com/assets/12807846/23821620/25a3c3e4-065e-11e7-9a67-8602a95f7a38.png)

**Expected**
For all the search results the name of the room must be displayed.

**Comment by Princu7** [comment]
Nice find. Thanks for opening the issue :)

**Comment by sumedh123** [comment]
@Princu7  @geekyd  I did not understand what's the issue about. Can anyone explain me?

**Comment by Princu7** [comment]
The Artificial Intelligence session should come under the room Annexe Hall after searching. As you see from the screenshots above, the visible sessions after search don't have the room name above it. So we can't use the nav-bar for navigating the session based on the rooms in which they take place. This is the issue here.
