### ISSUE TITLE
Create a screencast showing the main features of the Open Event Web App

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1159]
Please create a 1.5 minute screencast with the main features of the generator and app:

* Show how to import an Open Event file and generate a website.
* Show the pages of the website.
* at the end show the GitHub page of the project
* do not show any subtitles

**Comment by geekyd** [comment]
@mariobehling I'm on it :)

**Comment by geekyd** [comment]
@mariobehling Please check this 
![cast](https://cloud.githubusercontent.com/assets/12807846/23825674/f851a9dc-06b3-11e7-83a4-a313a4940663.gif)

**Comment by mariobehling** [comment]
@geekyd Looks good, but we need a video in high resolution. What is the highest video resolution you could make this?

**Comment by Princu7** [comment]
Great content. The video seems to lag a bit. Would be great if you could remove it. 
@mariobehling  @geekyd 
Also, since the screencast is to be shown at the FOSSASIA Summit, it would be better IMO to generate that via the app. The event is big and generation through the API endpoint will take some time, but we could fast forward that part easily. Showing the generated website of the current event should appeal more to the attendees. I might be totally wrong, though. Would love to hear your opinions. Thanks!!

**Comment by geekyd** [comment]
@mariobehling The output i sent is a gif, I converted it to show the content. My screen resolution is 1280 X 800. 

@Princu7 Thats a great idea, it would be perfect if we can fast forward the generation part and concentrate on the generated app.

**Comment by geekyd** [comment]
@mariobehling @Princu7 Please check these links to the youtube videos

[Demo without deploy](https://www.youtube.com/watch?v=fuKIfpNeDrQ)
[Demo with deploy](https://www.youtube.com/watch?v=FUOxzXx9e_s)

**Comment by Princu7** [comment]
@geekyd Content looks really good. Nice.

**Comment by mariobehling** [comment]
@geekyd Could you provide a downloadable file, please?

**Comment by geekyd** [comment]
@mariobehling Please use this link to download the video.
https://drive.google.com/open?id=0BwWgyD2HJorUdy1WY2d4WjFsck0

**Comment by mariobehling** [comment]
Excellent job! Will play it at FOSSASIA Summit!
