### ISSUE TITLE
Inconsistency among the scroll bar's position

### ISSUE THREAD

**Issue by daminisatya** [fossasia/open-event-webapp#116]
When you check out the sessions page, speakers page and tracks page. The scroll bars seem to be dependant on the other page's scroll position. When you scroll the bar to a particular position in one page, the position of the scroll bars in the other two are changed inconsistently. 

Steps to reproduce
------------------------
1. Make sure all the scroll bars are at the top.
2. Go to sessions page and scroll down all the way(the outer scroll bar)
3. Go to either speakers or tracks to observe the change in the scroll bar position. 

This was observed in chrome browser (Ubuntu)

**Comment by SaptakS** [comment]
I think this is because the scroll is in the entire right container and not particular to the controllers being loaded. For Session page we can handle this by hidding overflow in the parent container and letting the md-content loaded from session have the overflow. For Speakers, Tracks, we need to change the format of md-content to achieve this. @championswimmer @creativepsyco opinion?

**Comment by ashutoshsaboo** [comment]
@SaptakS @joerx @daminisatya @mariobehling @jig08 @AmayAgrawal @championswimmer I have pushed a PR - https://github.com/fossasia/open-event-webapp/pull/135 which resolves this issue. Could someone review the PR, please! Thanks! :smiley:

**Comment by aayusharora** [comment]
@ashutoshsaboo , Please remove the conflicts so that it can be merged.
