### ISSUE TITLE
Images of speakers not showing up on tracks and other pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1164]
After the revert of the lazy loading the images do not show up anymore on a number of pages.

**Comment by geekyd** [comment]
@mariobehling please revert #1141 as it adds lazy load to all the pages.

**Comment by anu-007** [comment]
@geekyd reverting #1141 may resolve the issue but leaves a console warning related to jquery.lazyload.js which is caused due to preloading of this js file so we have to remove preloading of this file also for no console warnings. I have sent a PR solving this issue ( https://github.com/fossasia/open-event-webapp/pull/1165 ) without any warning. thanks !!

**Comment by Princu7** [comment]
This issue has been fixed. Thanks @anu-007
