### ISSUE TITLE
Rooms : Multiple nav bars for spanning through the results

### ISSUE THREAD

**Issue by anamika2910** [fossasia/open-event-webapp#1176]
Currently on the rooms page, there are two navigation bars available - one which navigates to a part of the results on basis of the date and the other one navigating on the basis of date and the room. Also, if no search results appear for a particular queried term in the search box, no results is shown just below the first nav bar, leading to a page like this -

![screenshot from 2017-03-16 16 57 11](https://cloud.githubusercontent.com/assets/11133538/23994640/d7538244-0a6b-11e7-8558-c27f14a780b1.png)

"No matching results found"  should come below the second nav bar, also requirements fulfilled by both the  nav bars, can be met with one navigation bar.

**Comment by Princu7** [comment]
@anamika2910 Hello. Thanks for opening the issue. The part about having two navigation bars seems understandable since the second bar containing the different tracks kind of already does the job of the first one. But we also have to ensure that the design also stays consistent on the tracks page. Also, the position of 'starred button' will have to be changed a little.

Let's wait for more inputs on this issue :)

**Comment by aayusharora** [comment]
According to users feedback, @princu7 the two bars seems confusing.
We can do the same set of functionalities by second bar only. 
@anamika2910 Thanks.

**Comment by Princu7** [comment]
@aayusharora Exactly. Thanks for the input :) @anamika2910 Would you like to work on it?

**Comment by anamika2910** [comment]
Yes, I would.

**Comment by aayusharora** [comment]
Closing via #1206
