### ISSUE TITLE
Propose steps to develop app as Progressive Web App

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1228]
What is required to make the result of the app generator into a progressive web app? Please propose steps and technology changes that are necessary.

**Comment by Princu7** [comment]
@mariobehling Sorry. Been busy due to academics. The steps for the offline capabilities and transformation into progressive web apps have already been discussed in #1218. The heart of the PWAs are the service workers which are basically javascript scripts which run in the background and intercept the requests made against the registered domain and have the ability to create a custom made response to that request if desired. With the help of service workers, we can make the web app functional offline and also add other features like push notifications and background sync.

**Comment by Princu7** [comment]
@mariobehling 
Basic steps would be as follows:
* Install, register and activate service workers on the generated sites
* Create a web-app manifest
* Add support for caching
* Make custom fallback pages in case of cache failure
* Check for cache invalidation
* Enabling push notifactions with help from server side

No major changes in technology are required. We have to enable HTTPS on the Github pages of the official repo for the changes to take place. Also, we would have to use a database for storing the notifications data which will be used for sending the push notifications to the user.

**Comment by geekyd** [comment]
@mariobehling Service workers are the heart of the progressive web apps. Service workers will let us enable offline mode, push notifications and background sync. One important thing to consider is that service workers only work over `HTTPS `protocol.

The first step would be to enable HTTPS on the gh-pages so that the PWA features can be reflected.

Steps to PWA

**Offline mode**
1. Install and register the service workers.
2. Adding offline mode using the `fetch` event of the service worker.
3. Creating a fallback for caching.

**Push notifications**
1. Adding required jsons for push notifications(for GCM).
2. Creating a notification server with database to store all the notification data.
3. Adding push notifications using the `push` event of service worker with the server.

**Comment by anu-007** [comment]
@mariobehling following steps will demonstrate how to develop app as progressive web app -

**1. Adding a Web app manifest file -** this will describe meta information about a site and control how our it might look when added to a user's home screen.
**2. Adding a service worker -** It is a background script that a browser can run even while a user isn't on our page, this will provide offline support, and wakes up when a notification is triggered.
**2.1** Register a service worker- this is done by adding a small script in event.hbs which checks if the browser supports service worker or not if it supports then it will tell where is our service worker javascript file is located.
**2.2** Creating our service worker script which handles install, fetch, activate events etc. in which we open a cache, cache our files and Confirm whether all the required assets are cached or not, serve the requests from service worker, decide which service worker will be activated currently etc.
**3. Adding push notifications -** push event is invoked when a server supplies information to a service worker then a notification is generated as an action of service worker showing information to a user.
**4. Adding Background sync -** this enables to update our assets in the background even when we are not using our app it helps in keeping up to date with the version of our web app.It can be done by adding a revision (a hash) with a file name that we cached so every time when a file has updated the hash associated with it also changes which a service worker detects and download the updated assets.

I made a video on adding a service worker and caching some assets from a generated web app ( [https://youtu.be/91uug0GuXhw] ).

**Comment by mariobehling** [comment]
@Princu7  
> Also, we would have to use a database for storing the notifications data which will be used for sending the push notifications to the user.

Push notifications are nice, but if they require a database it would mean we cannot use Github Pages anymore. Can we do without them?

@Princu7 @anu-007 

> The heart of the PWAs are the service workers which are basically javascript scripts which run in the background and intercept the requests

Do these scripts run on Github pages?

**Comment by geekyd** [comment]
@mariobehling We will be able to use Github pages even after we introduce the notification feature for the generated webapp. We will be using the existing generator server for notifications.

High level explanation of approach:

1. We will be creating an api for push in the generator that will be triggered by the generated web app when ever a user bookmarks an event. which will trigger the api for storing the notifications using a post method in JQUERY.
2. On the generator server we will be having a database for the notifications which will store the information corresponding to the uuid(unique id generated when we register push services) of the user.
3. We will run a schedular every 24 hour and create a queue of all the notifications to be sent, and push them at required time.

> Do these scripts run on Github pages?

Yes these can run on the gh-pages but we will be needing HTTPS turned on for the repo.

**Comment by sumedh123** [comment]
@mariobehling @geekyd  We will require application server. The architecture is 3-tier, i.e Client, Push messaging server, Application Server. The service workers run on github pages but the main problem is that without application server we cannot store the subscription ids of the clients. One way is to implement API.

**Comment by mariobehling** [comment]
@geekyd @sumedh123 Our generator server is not supposed to be a reliable solution. The beauty of the web app is that it can run without any server anywhere. We already have a solution that requires a server -> the open event orga server. We can implement anything that requires a server here. 

What parts can be done without a server? Does this make sense at all if we don't have a server?

**Comment by geekyd** [comment]
@mariobehling 

> We already have a solution that requires a server -> the open event orga server. 

Yes thats a great suggestion. Totally makes sense as we already have an api server at the orga server. We can implement the notification services on the orga server and keep the web app independent of it server. 

> What parts can be done without a server?

We can implement offline features of PWA without any server as demoed  by @anu-007 . There shall be no problem in doing this for the generated web-app.

**Comment by mariobehling** [comment]
> We can implement offline features of PWA without any server as demoed by @anu-007 . There shall be no problem in doing this for the generated web-app.

Ok, thanks for clearing up the question. Please open issues to get this going. Cheers.

**Comment by Princu7** [comment]
@geekyd @sumedh123 Thanks for the explanations.

@mariobehling Yes, we do require a server for push notifications since we would need a server to store the details of the future event sessions and send them at the appropriate time. 

Yes, we can use the orga-server for sending the notifications. But, that would be kinda putting additional load on the server. It is already used for a variety of tasks and including this task of sending notifications would increase the load both on the server and the database. We already have a generator server which is used for generation of web app directly and also provides a `REST API` which will provide support for generation from external sources like `orga-server` and `SUSI`. Why not leverage this generator server instead of using orga-server for notifications. We already rely on it for many purposes. We would need to implement additional APIs for notifications for doing the task. It will keep the client-side app's code separate from the server side and reduce the additional load. Only the notifications feature of the web apps would require the generator server. And it would continue to function even if the generator server goes down for some duration. I made a prototype showing the steps required. Please guide. Thanks!!

[![dfd2.png](https://s3.postimg.org/dmqchpe3n/dfd2.png)](https://postimg.org/image/kpy7xbjj3/)

![Notification](https://image.ibb.co/jDRztv/push_notification.png)

**Comment by geekyd** [comment]
We need to evaluate the pros and cons of using orga-server and generator-server for implementation of the notification services. I have made some points please have a look.

**Orga-server**
Pros:

- We will have a centralised notification service that can be extended to other apps like android application of the event.
- We already have a structured framework for designing the api.
 
Cons:
- The server already does many things and implementing the notifications will increase load on the server.

**Generator server**
Pros:
- We can create the notification server without increasing any load on the server.
- The notification server will be independent of the server.

Cons:
- The notification services will only be confined to the web app and not other applications.

One thing that can be done irrespective of the platform to be chosen, is we can have a notification service implemented and provide some handy features to the organiser of the event.
eg. The organiser can push a notification, reminder or update to all the users who have installed and used the application. Some thing like major e-commerce sites do.

Please add more to the pros and cons list and share your opinion on this.

**Comment by mariobehling** [comment]
@Princu7 My question was mainly intended to understand how we can make the app work offline. I don't worry so much about push notifications at the moment. Nice feature, but not essential at this point. We have more basic stuff to worry about, e.g. loklak/Twitter integration is not working right now.

So, I understand: We can have offline functionalities without an additional server. This is all that is needed right now.

Push notifications can come later and we can come back to this once the more basic requirements of this service are met.

**Comment by Princu7** [comment]
@mariobehling Ah. No problem at all. We can have more detailed discussions later on it. The first step is to make the app work offline. I created some issues regarding the offline features #1218 and #1219 . Will start working on it soon.

**Comment by mariobehling** [comment]
Please follow up on the implementation of offline functionalities here https://github.com/fossasia/open-event-webapp/issues/1247

Thanks everyone. Excellent discussion!

**Comment by mariobehling** [comment]
@Princu7 Ok, if any issue are duplicate, please close. Only thing, I would like to ask you, please ensure we don't need to store a DB of data of events on the server. This would mean we need to take care of migrations etc. Keep it lean, please. Avoid any dependency of the app on the server. Thanks.
