### ISSUE TITLE
Implement offline features as PWA 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1247]
Please implement offline features of app as a PWA as discussed in https://github.com/fossasia/open-event-webapp/issues/1228.

The PWA functionality should be implemented without any requirement of a server at this point of time.

**Comment by anu-007** [comment]
@mariobehling  first of all, sorry for the late response as my exams are currently going on.

I like to add more on push notifications that we do not need any external database or server for notifications we can store relevant data in browser's indexedDB (like sessions alerts and bookmarked sessions information etc.) also there is no need of any server for this purpose we should use notifications which are pushed locally instead of pushed by server as in our web app we only want to display notifications about sessions currently going on and bookmarked sessions this is very basic task and I think it will be not appropriate to use a new server and database for doing only this task which can be performed locally using local notifications and indexedDB.
As we can extract the date and time to pop-up notifications from date and time as mentioned in sessions and the script will fire at that time to show that notification hence doing our work locally.
Although notifications pushed by the server has taken place of local notifications but in our case, i think we should stick to local notifications so I think we should tailor the features like notifications according to our needs instead of using conventional ones.Also, this will not have any effect related to the deployment of app anywhere like gh-pages etc. Thanks...!!!

**Comment by mariobehling** [comment]
@anu-007 Thanks for the input. We can come back to it once we have a need for notifications. For now we mainly need offline features. So, let's close the discussion on PWA now and get back to the code. We need  offline features. Cheers.

**Comment by anu-007** [comment]
@mariobehling sure we will first concentrate on offline feature first. Thanks...!!

**Comment by aayusharora** [comment]
Any updates on this @anu-007 ?

**Comment by anu-007** [comment]
@aayusharora I have not started to work on this issue as we have told to stabilize the web app first, but now I think it is right time to start implementing this feature, previously I have implemented some basic offline functionality to the web app which can be found here ( https://youtu.be/91uug0GuXhw ) so it does not take much time for me to implement it .I will start working on this and send a PR today.Thanks!!

**Comment by Princu7** [comment]
@anu-007 Thanks. Please add a very basic service worker first. Basic installation and fewer cache contents. We would then need to improve and discuss the structure of the service worker and add more features to it. We would also need to create fallback pages when the cache retrieval fails. We would have to be slightly careful on removing and old worker and activating a new one.

**Comment by anu-007** [comment]
@Princu7 ok I will take care of that.Thanks !!
