### ISSUE TITLE
Merge dev to master

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1254]
Please merge development to master branch. Ensure the branches are even.

**Comment by Princu7** [comment]
@mariobehling @aayusharora @geekyd @sumedh123 Currently, the master branch is 66 commits behind and 10 commits ahead of development. The reason why it is 10 commits ahead is due to the extra commits which have been introduced to the master previously when merging and reverting. If we merge the development branch to master now, the master branch will not be behind development but will become 12 commits ahead of it(2 extra commits due to merging). 

To ensure, that the two branches are even, we have to remove the extra commits from the master by resetting it to the development branch and force pushing it. This will make the two branches even. I tried this on my fork and it worked with master and development branches being even with one another.

https://github.com/Princu7/open-event-webapp/branches

But, I am not really sure this is the most efficient and correct approach and would like some suggestions and opinions before doing it. Please guide. Thanks!!

**Comment by sumedh123** [comment]
@Princu7 Was the previous merge of development to master reverted?

**Comment by Princu7** [comment]
Yes. It was reverted one time before. Also, whenever we merge a branch into another, there is an extraneous merge commit unless you are rebasing a branch on top of another. If you are interested in seeing the extra commits, then

`git rev-list  master --not development`
Will show the list of hashes of extra commits which are in master but not in development
`git rev-list  --count master --not development`
Will tell the number of extraneous commits

**Comment by mariobehling** [comment]
@the-dagger @mananwason @aayusharora @championswimmer Could you provide guidance on this issue, please?

**Comment by aayusharora** [comment]
@Princu7 I hope @niranjan94 can guide in this better. He has maintained the same for open-event orga.

**Comment by niranjan94** [comment]
@Princu7 .. 

In the orga-server, what we do is, we keep master in line with dev or behind dev. (never ahead). And fast-forward master to the required commit on dev whenever needed.

looks like your master is `10 commits ahead, 75 commits behind development`. Your first step would be to make is behind development.

**Comment by Princu7** [comment]
@niranjan94 Thanks. The reason why it is 10 commits ahead is due to the extra commits which have been introduced to the master previously when merging and reverting.

To ensure, that the two branches are even, we have to remove the extra commits from the master by resetting it to the development branch and force pushing it. This will make the two branches even. I tried this on my fork and it worked with master and development branches being even with one another.

But, I am not really sure this is the most efficient and correct approach and would like some suggestions and opinions before doing it. Please guide. Thanks!!

**Comment by niranjan94** [comment]
@Princu7 we can do what you suggested now. But the branch is protected and you will have to turn of branch protection temporarily before you do a force push to master.

**Comment by Princu7** [comment]
@niranjan94 Ok. Any other way around? Turning protection off would require admin access and would be slightly risky to do.

**Comment by niranjan94** [comment]
This is probably the cleanest way. So, it's alright. We can do this. 

I can force push it if you like.

**Comment by Princu7** [comment]
Oh. Thank you so much. Would be great if you could do so. Although doing it on my fork was easy and went successful, I would lie if I said I don't have fear and anxiety doing it on the official repo. If I could see and learn from you one time, I would probably have more confidence in dealing with this issue in future. Thanks for being so helping :)

**Comment by niranjan94** [comment]
@Princu7 done 😄  ...
No issue. Happy to help.

**Comment by niranjan94** [comment]
Force pushes are risky. So, we should avoid it much as possible. But some cases, especially when it comes to cleaning a repo, they're mostly unavoidable. 

Just ensure you double-triple check which branch you're on and which branch you're pushing to before you do a force push. Always, have a separate copy of that branch (checkout as a different name) you're pushing to so that even if your force push messes something up, you can always revert back.

**Comment by Princu7** [comment]
Thanks for the suggestions. I really like the one about keeping a backup branch to ensure we have something to revert to in case something went bad. Awesome tips. Thanks!!
