### ISSUE TITLE
Improving loading speed of the app

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1266]
Currently the whenever the page is loaded, the display() function is executed, which iterates over every session on the page to add star to the bookmarked sessions. This takes time as we iterates over DOM elements. The load time increases linearly with the number of sessions. 

One good solution would be to iterate the array stored in localStorage, instead of DOM elements.
Please suggest your solutions.

**Comment by Princu7** [comment]
Yeah, Agree. It would be much faster to iterate on the IDs of the bookmarked sessions in the localStorage instead of iterating through all the sessions. I was looking on the net for the time complexity of finding an element by its ID. I was delighted to know that the IDs are hashed and the complexity reduces to O(1)  which is the best as it can get. So, it seems to be the most efficient approach. We can test it out and compare the performance for validation.Thanks!!

**Comment by geekyd** [comment]
@Princu7 I will be sending a PR for the changes.
