### ISSUE TITLE
Implement support for json-api 

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-webapp#1322]
The Open Event Server is moving towards a new API as per the [json-api specification](http://jsonapi.org/). Hence all the client apps need to support the same. 

You can checkout some of the javascript client libraries that you can use to easily consume the API at http://jsonapi.org/implementations/#client-libraries-javascript. 

Please note that the zip format is not changing and only the API format is and the android app needs to support both. (Incase the user uploads a zip and generates an app.)

**Comment by Princu7** [comment]
I have researched a bit on this issue. I am currently trying out the new API of the server. Also, the guys at Android have built a [sample mock JSON response](https://github.com/iamareebjamal/open-event-android-sdk/tree/master/src/main/resources) of the server to work with till the API is fully functional.
In order to make minimal changes to the generator, we will aim to convert the incoming response into the current model which the generator uses. Also, since many of the names of the attributes have changed, we have to incorporate that into the generator. But we can't do it directly since all the sample currently uses the old attributes.

Since the work is big and we don't want to incorporate the new changes immediately, I can make a branch in my repository and work on it. When the new API is fully functional and all the samples have been updated, we can merge it into the main repo. @aayusharora What do you suggest? Please guide. Thanks!!

**Comment by Princu7** [comment]
I am making a list of the attributes which have changed in the new API implementation. When the zip samples and the new API is enforced, we would have to change them in order for the generator to work properly. There might be some fields missing which I will add as I look into the new models and the current generator implementation in more detail.

**Comment by Princu7** [comment]
**Event Model**

* `start_time` changed to `starts-at`
* `end_time` changed to `ends-at`
* `logo` changed to `logo-url`
* `location_name` changed to `location-name`
* `social_links` changed to `social-links`
* `license_details` changed to `license-details`

**Comment by Princu7** [comment]
**Track Model**

* `font_color` changed to `font-color` 

**Sponsor Model**

* `sponsor-type` changed to `type`
* `logo` changed to `logo-url`

**Speaker Model**

* `short_biography` changed to `short-biography`
* `long_biography` changed to `long-biography`
* `featured` changed to `is-featured`

**Comment by Princu7** [comment]
**Session Model**

* `start_time` changed to `starts-at`
* `end_time` changed to `ends-at`
* `session-type` changed to `session-type`
* `short_abstract` changed to `short-abstract`
* `long_abstract` changed to `long-abstract`
* `slides` changed to `slides-url`
* `audio` changed to `audios-url`
* `video` changed to `videos-url`

**Comment by aayusharora** [comment]
Thanks @Princu7 please proceed.

**Comment by Princu7** [comment]
@niranjan94 @aayusharora Do we have to keep the support for the legacy attributes or remove it altogether? Implementing legacy support only for a short time when we are completely shifting over to the new API format and updating the samples does not seem much fruitful to me. Please guide on this issue. Thank you so much :)

**Comment by Princu7** [comment]
I have created a branch in my forked repository and doing the work related to the implementation of the new API format there. It is here:
https://github.com/Princu7/open-event-webapp/tree/changedFields

**Comment by Princu7** [comment]
A basic part of the work is done. I have replaced the old attributes that have changed with the new attributes (all of them are mentioned in the posts added above). And it works well with the zip which has been updated according to the new API specifications.
The changed zip is [here](https://github.com/fossasia/open-event/pull/192)
The test server is [here](https://shrouded-ocean-89460.herokuapp.com). Use this API endpoint for testing https://raw.githubusercontent.com/arp95/open-event/1bd4b1417271fbbfa6095c2ad6a62f3b7b38dcaf/sample/FOSSASIA16/event

**Comment by Princu7** [comment]
The next part is to support fetching of the data in accordance with the new API specifications and converting it into the supported model right now. Testing out the new API and working on implementing it. The speaker API to get all the speakers of an event is not ready right now but will complete the work on rest of the models completely.
