### ISSUE TITLE
Scrolling on pages very slow

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1328]
There is some kind of delay that got in at some of the recent commits. The scrolling on pages is delayed for no reason.

I don't see a feature request where this has been requested. Please ensure PRs only change what has been mentioned in the issue and PR to avoid such new issues.

**Comment by Princu7** [comment]
@mariobehling It's kinda hard to reproduce this issue. It works fine for me. It only lags a little on the schedule page for a small moment though. Can you please elaborate on this issue? Thank you so much.

@aayusharora @geekyd Please help in regards to this issue. Thanks!!

**Comment by aayusharora** [comment]
@mariobehling It works for me. Can you elaborate where it is happening exactly?

**Comment by Princu7** [comment]
@aayusharora I have looked in detail at this issue and what it seems like is that the lazy load is not working on this page. So, on a fresh visit to this page, all the images are loaded from the internet even though the user does not scroll even a single pixel.

Loading of all of the images take some time and it is what delays the scrolling on the page. After few visit to the page, the contents get cached so it does not take much time then and it appears normal. I will try to look into the reason why the lazy loading is not working and try to fix it. Thanks :)

**Comment by aayusharora** [comment]
Hmm, I hope this is right. Let's check how this is removed, as it was there in the previous version.

**Comment by Princu7** [comment]
@aayusharora I don't really know. It works on the other pages but not on the schedule page. It is happening because the images are invisible inside the collapsed containers. At first, I thought this was some problem with the current library, so I began looking for a new one.

I stumbled across this. It seemed to be much better and actively maintained by the developer. So, I thought of using it but the same problem occurred again. So, to get more help, I opened an issue on that repo https://github.com/verlok/lazyload/issues/105

and also created a codepen link to isolate the problem and present it easily
https://codepen.io/ShortAndSimple/pen/gRKBEg

There has been some discussion there. What is seems possible at this moment is that the image is lazy fetched when the user clicks on the session element. The images are invisible initially (parent container div has `display: none` set) so loading them in the background is not working. I have asked for more help on this issue. Let's see what he says.

**Comment by Princu7** [comment]
@aayusharora So, after long discussions with the developer (see it [here](https://github.com/verlok/lazyload/issues/105), it does not seem possible to be lazy fetching the images in advance on the schedule page. They are inside the collapsible parent container having `display: none`, which means that their position can't be determined and hence they can't be properly fetched. 

The best solution it is to fetch the image only when the user clicks on the collapsible session element. Before that, we don't fetch any image. It would also help in reducing the bandwidth wastage on the user part. Please guide whether I should proceed it with or not. Thanks!!
