### ISSUE TITLE
Misaligned sessions in calendar view

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1350]
**Actual Behaviour**
![screenshot from 2017-06-19 06-15-39](https://user-images.githubusercontent.com/12807846/27265731-4e58b1a8-54b7-11e7-98fa-382f77713766.png)

**Expected Behaviour**
The pop-box should be aligned in a similar manner as in speakers page.

@Princu7 The sessions in calendar view got misaligned due to recent changes, can you please check. Thanks!

**Comment by Princu7** [comment]
@geekyd This was really weird and coincidental :smile:. I had added a class named `session-container` in the single session file. I checked the `application.scss` file for this class name and found none so I thought that no element is using this class. Turns out, the sessions on the schedule page were using this class with nothing in it prior to the previous commit merged. Since there was a property of `text-align:center` in the recent commit in the `session-container` class, the items got misaligned. I will remove the class session-container from the schedule page to fix the error. Thanks for this :)
