### ISSUE TITLE
Only show sections e.g. featured speaker or sponsors if data is available

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1366]
Some events don't have featured speakers or sponsors. Only show a section if data for that section is available.

**Comment by Princu7** [comment]
@mariobehling Yes. We are already showing those sections only if they exist. In the Mozilla All Hands 2017, there is information about the sponsors. That's why it is showing up. If we remove it, then the section would also be gone. Please check it below. Thanks!!

https://github.com/fossasia/open-event/blob/master/sample/MozillaAllHands17/sponsors

**Comment by aayusharora** [comment]
Data is available now. Closing this.
