### ISSUE TITLE
Application gets stuck when generate webapp button is clicked second time without refreshing the page.

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event-webapp#1449]
**Actual Behaviour**

The application gets stuck when generate webapp button is clicked second time after completion of first process either with wrong API endpoint link or with right one.

**Expected Behaviour**

Generate webapp button should be permanently disabled after generation of website , so that page needs to be refreshed after one use.
Or proper website and errors should be thrown second time also depending on request parameters.

**Steps to reproduce it**

Generate a webapp with proper endpoint link , after its creation press generate webapp button again with same API end point link or some other.

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.
![screenshot from 2017-08-19 19-35-00](https://user-images.githubusercontent.com/21157929/29487445-a93b7198-8516-11e7-805a-31bbc52aff91.png)

**Would you like to work on the issue?**
Yes,I would like to work on it.

**Comment by Princu7** [comment]
@agbilotia1998 Thanks for opening the issue :) There are a bunch of things that we need to care of in the generator form. Many issues are there in it. I will open a parent issue containing the list of things that we need to fix and we can then discuss and work on it :+1:

**Comment by Princu7** [comment]
@agbilotia1998 I guess the user shouldn't have to refresh the page in order to generate the app again. Currently, it happens that when we generate an app using API endpoint, we are not able to generate a different app by entering a different endpoint. It shouldn't happen.

Also, there are some other issues:
* The cancel button doesn't work when the zip upload is selected and the app is in the generation process.
* When generating through the API endpoint, there is no cancel button which the user can press to stop the process. He has to either wait for the entire duration or refresh the page.

First we can take care of this issue, after that we can start working on the two points mentioned above. Thanks!

**Comment by agbilotia1998** [comment]
Okay should I start working on this issue?

**Comment by Princu7** [comment]
@agbilotia1998 Yes. Please go ahead. Thanks :)
