### ISSUE TITLE
Autogeneration from API not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1468]
There is an organizer who tries to generate an app with the API https://eventyay.com/api/v1/events/257 on https://webgen.eventyay.com/

The generation stops at 50% on http://opev-webgen-dev.herokuapp.com/

**Comment by Hardik113** [comment]
Sir I have identified the bug and I am working on it. Its just that the data we are getting from the API is not consistent with key values in our file.

**Comment by Hardik113** [comment]
Also sir to be on a safer side we need to adapt a convention so that we can remain consistent along all the three platforms of uploading-data. Eg fold.js is using [photo-url] but the API is sending us data as [photo_url]. Let me know how we can proceed.

**Comment by Princu7** [comment]
@mariobehling @Hardik113 The concerned event has been created on the old server which contains the outdated attributes. We have now moved to the new API model of the open event server in which attribute names differ a little and hence the generator doesn't support the events created on the old server. It will only work for the events with the updated attributes and created on the new server. (http://open-event-api.herokuapp.com)

This is the commit where the updation to the new API model was done https://github.com/fossasia/open-event-webapp/pull/1448.

**Comment by Princu7** [comment]
@mariobehling What we can do as a backup is that we create an old legacy Heroku server which supports the old attributes and the organizers can generate the webapp for the events created on the old eventyay server there. This way, we don't have to retract the progress back or temporarily add support for the old events.

**Comment by Hardik113** [comment]
@Princu7 Currently the EventYay App is making a response with key values like social_links: []. But the current event generation platform is (generator.js, fold.js) are using social-links:[]. Which is causing the mismatch so how do you propose to solve this issue.
![screen shot 2017-09-10 at 7 33 11 pm](https://user-images.githubusercontent.com/18461983/30249704-3d3f0a0e-965f-11e7-91a3-b275e13662f3.png)

**Comment by Princu7** [comment]
@hardik Please understand. This is a little confusing :smile: There are two eventyay servers: one recently developed during the GSoC 17 and the other developed earlier. The format of the response and the attributes returned in the new eventyay server is a little different. The new eventyay server is JSON API Compatible. You can see it here. http://open-event-api.herokuapp.com. The response from the old server.

The webapp has been updated to support events created on the new eventyay server. Since the event mentioned here is created on the old server, the webapp is not able to generate an event website for it.

The change in the webapp generator to support the new eventyay server was done in this PR https://github.com/fossasia/open-event-webapp/pull/1448. We can create a test server running on the code made prior to that PR. The old events can then be generated on that test server.

**Comment by Princu7** [comment]
This might help!
https://blog.fossasia.org/open-event-ecosystem/

**Comment by Hardik113** [comment]
Yeah Got it!

**Comment by mariobehling** [comment]
@Princu7 Would be great if you could create a legacy server. Even better would be if the old and new format could be supported. We have a running system and it does not work as expected for people. I cannot deal with explaining people that we have different formats.

Well, maybe a work around for now is a legacy server. Could you ping me on chat please when it is up and running? Thank you.
