### ISSUE TITLE
Cannot generate App from current Eventyay deployment

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1726]
The app does not generate a site using the API of the current site: https://eventyay.com/api/v1/events/275

It gets stalled at 50%.

![screenshot from 2018-02-22 00-12-05](https://user-images.githubusercontent.com/1583873/36510924-0ed09e30-1765-11e8-8d0f-dceb3a6bcb63.png)

**Comment by rohan598** [comment]
Can I work on this issue @mariobehling ?

**Comment by mariobehling** [comment]
Just go ahead and make a PR.

**Comment by ParthS007** [comment]
![image](https://user-images.githubusercontent.com/24358501/36541827-2d933922-1805-11e8-82ce-ea096a8c4b0f.png)
@rohan598  Please go through these logs. This will help for sure :+1:

**Comment by rohan598** [comment]
Actually, I have partially corrected this issue. The new issue which has propped up is that after compiling SASS (70%), it is giving me a zip error. I am on it at the moment. I’ll share the details as soon as possible.

**Comment by ParthS007** [comment]
@rohan598 Can you please share the logs of the web app generation after the changes?

**Comment by rohan598** [comment]
I have pinned down to two problems
1) jsonapi-serializer (npm-package) : - This is only used for deserializing and not for serializing which produces an undefined json. This is because the package requires data (in this case response data) to be serialized first ( a specific format) and then deserialize it.
2)There is naming mismatch in the json properties and the names used to refer to them, namely '-'has been used instead '_' and the object demands '_'.

I am working on the second one at the moment. I have got some success with it and about the first one it has been resolved.

**Screenshots: -** 
**googlechrome inspector**
![screen shot 2018-02-23 at 2 06 22 pm](https://user-images.githubusercontent.com/25100847/36585533-3eca819c-18a4-11e8-91e5-de897c53dc95.png)
![screen shot 2018-02-23 at 2 06 37 pm](https://user-images.githubusercontent.com/25100847/36585537-41be6814-18a4-11e8-9c23-2be14ad50e88.png)
**node console**
![screen shot 2018-02-23 at 2 09 37 pm](https://user-images.githubusercontent.com/25100847/36585563-6628a386-18a4-11e8-9baf-e05888e30a67.png)

**Comment by agbilotia1998** [comment]
@rohan598 the data in API is according to older API version.Hence this sample won't be generated by current version of webapp generator.

**Comment by rohan598** [comment]
The issue has almost been resolved as I have made data compatible with the new api.

**Comment by rohan598** [comment]
The error I am getting now is
```
vips warning: linecache: error in tile 0 x 1576
Error: vipspng: Read Error
vipspng: Read Error
vips warning: linecache: error in tile 0 x 2408
```
(This is just one instance, this error repeats for each image  which is downloaded)
Any suggestions to correct it?

**Comment by rohan598** [comment]
The issue has been resolved and the web app generator is working well with the latest version of the api. I'll be sending a pull request for the same.

**Screenshots**
![screen shot 2018-02-23 at 9 51 08 pm](https://user-images.githubusercontent.com/25100847/36604814-c8902748-18e4-11e8-8e2a-43b7557a4dc6.png)

![screen shot 2018-02-23 at 9 48 29 pm](https://user-images.githubusercontent.com/25100847/36604803-c159602a-18e4-11e8-9838-f5f57db0aa9a.png)

**Comment by agbilotia1998** [comment]
@mariobehling this can be closed.

**Comment by ParthS007** [comment]
Closing as app is generated :+1:
