### ISSUE TITLE
Error while generating preview.

### ISSUE THREAD

**Issue by jainaman224** [fossasia/open-event-webapp#425]
I am receiving following error when I generated and preview web app using mock json.

{ [Error: EISDIR: illegal operation on a directory, open '/home/jainaman224/open-event-webapp/src/generator/backend/../../../dist/img/speakers/']
  errno: -21,
  code: 'EISDIR',
  syscall: 'open',
  path: '/home/jainaman224/open-event-webapp/src/generator/backend/../../../dist/img/speakers/' }

**Comment by championswimmer** [comment]
Which assetmode option you used ? Link or Download ?

**Comment by jainaman224** [comment]
Download locally with website.

**Comment by jainaman224** [comment]
I am getting following error.
![Error window](https://cloud.githubusercontent.com/assets/13117482/16664130/67381352-449c-11e6-929e-5a94f0b3198f.png)

**Comment by jainaman224** [comment]
What data do you want inside folder dist/img/speakers/ . Do tell me, this data is missing from this folder.

**Comment by aayusharora** [comment]
@jainaman224  Inside this path, images are downloaded by the URL of images provided in speakers.json.

**Comment by aayusharora** [comment]
@jainaman224 Followed by gitter discussion, I have rechecked the code and as I suggested earlier the error was due to broken links of images in speakers.json. This is only a mockjson. Links like https://raw.githubusercontent.com/OpenTechSummit/2016.opentechsummit.net/gh-pages/programm/speakers/Andr\u00e9_Rebentisch.jpg are broken.There are 11 such links hence 11 errors in console.
