### ISSUE TITLE
Send out an email with a download link after website is generated

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#509]
The Android app generator already offers this and it would be great if we could have it implemented in the same way in both app generators.

Please implement:
- [x] Send out an email with a unique download link
- [x] Use a hash to make the download link unique
- [x] The download should be possible for 72 days after that the apk gets automatically deleted from the server
- [x] Document it in `dosc/AppGenerator.md] (how to change the parameters (send out email, documenting hash implementation, download location of apk, automatic time before apk gets deleted)

Related to: https://github.com/fossasia/open-event-android/issues/508

**Comment by championswimmer** [comment]
@mariobehling heroku does not provide persistent storage

files are valid only till the server sleeps next time 

also websites generated can be 500mb in size (OTS16 with audio is 532mb). such large websites cannot be saved in large numbers on server

**Comment by mariobehling** [comment]
Please use the FOSSASIA sample. We are using Heroku for development. The final apps should work on the cloud or normal server. File storage should use Amazon S3 just like the server. I see two ways we need it a) Integrate the web app with Amazon storage itself. b) Access the S3 Storage of the server probably through an internal API. Please open issues for required components.

**Comment by mariobehling** [comment]
Please also check the options in the admin settings (https://open-event-dev.herokuapp.com/admin/settings/). Actually, there is the choice of local storage or S3. In any case, you should use whatever is the choice in the settings.

![screenshot from 2016-08-01 16 37 15](https://cloud.githubusercontent.com/assets/1583873/17297536/63b874ec-5806-11e6-87f0-f11744013b84.png)

**Comment by championswimmer** [comment]
Okay ! Will set it up using S3 then

**Comment by championswimmer** [comment]
@mariobehling but these keys can be available to webapp generator only when used as a microservice of orga-server

But if used without the orga-server, then I'll have to ask each user for amazon s3 key every time they generate ?

**Comment by mariobehling** [comment]
> but these keys can be available to webapp generator only when used as a microservice of orga-server

Yes, there needs to be an internal API for you to access. Please file an issue on the server for that.

> But if used without the orga-server, then I'll have to ask each user for amazon s3 key every time they generate ?

You need to set up a test server and create an Amazon bucket for the service, not every user needs one.

The details for that should be in the config file I asked about a few days ago.

**Comment by Princu7** [comment]
@mariobehling I am willing to give this issue a go. I may need some guidance since I have not used amazon web services before. :smile: 

I was thinking of integrating the amazon web services with the webapp itself instead of depending upon an internal api from the orga server. I was searching on the net for the options and found the official aws sdk for javascript which can be used for the upload of the zip files directly to the s3 after entering the required configurations and credentials. In order to let user download the zip file, we would also have to make the bucket public. We can use the javascript library crypto for generating the hash. This should work in my opinion. 
Please give your thoughts and suggestions. Thank you!!

**Comment by mariobehling** [comment]
@Princu7 Yes, it is a valid idea, but it is preferable not to depend on Amazon only here. It looks like in future we will host the service on Google Cloud, but other options are also possible and if the user chooses "local" then it should work locally as well.

Please help to implement an abstracted solution, that can be used with different services. Thank you.

**Comment by Princu7** [comment]
@mariobehling Thanks for explaining but I am afraid that I didn't fully understood it. Would you please elaborate the problem with the proposed solution and suggest an alternative please? 

We will be just using the amazon aws s3 only for storage purposes and nothing else. Considering our app is currently deployed on heroku and since heroku doesn't provide persistent storage, it is a quite good option. In the future we might shift to google cloud which does provides persistent storage. In that case, we can change the storage device if needed. It doesn't really matter where our app is deployed, we are just using aws s3 for storage of the event folders and nothing else. Sorry for the confusion and inconvenience. Thank you!!

**Comment by mariobehling** [comment]
@Princu7 Ok, yes that sounds good. Sorry, I misunderstood. My first understanding was, that we will depend on mailing services of Amazon. Storage is straight forward though. Thanks for the details. Please go ahead.

**Comment by Princu7** [comment]
@mariobehling @aayusharora I have almost completed this issue. As a demonstration, here is the deployed app on heroku which uses amazon s3 for storage of the event folders.

https://warm-lake-95173.herokuapp.com 

When we click the Download button, event folder is automatically downloaded from the s3 storage. Here are some screenshot-
![screenshot from 2016-11-06 09-41-44](https://cloud.githubusercontent.com/assets/8847265/20035340/d6a92096-a405-11e6-9730-2bc4390c5bd8.png)
![screenshot from 2016-11-06 09-41-58](https://cloud.githubusercontent.com/assets/8847265/20035344/e589073e-a405-11e6-8d13-2188ba0d0337.png)

Regarding sending of email, since I don't have a _sendgrid api key_, the email is not send to the user. But it should presumably work fine when it is merged in the main branch. However there are some conflicts-

1. Currently I am using my _amazon aws access key id and secret acess key_. Should we continue to use it or use the _FOSSASIA_ account for credentials?

2. We have to keep the above keys secret. Now there are two ways to do that. First to set them directly as _config variables_ in the _heroku dashboard_. This can be done only by you Sir @mariobehling . Here is a link for that just in case. 
https://devcenter.heroku.com/articles/config-vars
Other option is to write them in _.travis.yml_ file and _encrypt_ it. Both are valid options.

Please test the above app and guide on what to do further. Thank you!!

**Comment by Princu7** [comment]
@mariobehling Please review this issue. Thanks!!

**Comment by mariobehling** [comment]
Thank you.

> using my amazon aws access key id and secret acess key

Yes, for the system, just set it up with your key quickly. We can change it then.

> option is to write them in .travis.yml file 

Yes, travis sounds good.

**Comment by Princu7** [comment]
@mariobehling I am really sorry for not reviewing the options properly. Since our app id deployed on heroku, encrypting the secret keys in the travis won't work since the travis is only on commits and pull requests. We have to set them up as config variables on the heroku dashboard. This can only be done by a person with write access to this repository and knowledge of the heroku credentials. The detailed process is described here
https://devcenter.heroku.com/articles/config-vars
