### ISSUE TITLE
Propose and implement a design with no scroll bars in the speaker section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#519]
Parent Issue: https://github.com/fossasia/open-event-webapp/issues/515#issuecomment-234709757

Propose and implement a design with no scroll bars in speaker section (make a screenshot how it will look like.

**Comment by aayusharora** [comment]
@mariobehling After taking lot of examples I think we should rethink this issue once
**Points to be considered**
1. We should have **fixed height** for each card otherwise it will give a very bad layout.
Example 
![badlayout](https://cloud.githubusercontent.com/assets/12194719/17259656/28d9e2ca-55ea-11e6-9050-cb07693c5066.png)
![badlayout2](https://cloud.githubusercontent.com/assets/12194719/17259662/2eb6627c-55ea-11e6-853b-de862b0d5a48.png)

2. When we keep this height fixed, we have to consider the speaker Bio coming from JSON which differs in content length.
Use case : some speakers have long Biography while others have small. 
3. To deal with variable data under a fixed container only scrollbar works best. We can take examples of websites like facebook having fixed height chatbox at left corner and a scrollbar only when it is hovered.

The same UX is here 
1. no scrollbar until the card is hovered 
2. no scrollbar if speaker bio content length is less than card length.
3. scrollbar when speaker bio length exceeds card length and user hovers the card.

**Comment by aayusharora** [comment]
@mariobehling I have tried  orga-server UI as it is without scrollbar. The UI does not seems good to me to deal with large text. I have tried **stress testing** and the results are not so good. There is no check of overflow which I am explaining here with scrollbars. Please check snapshot in the condition the data is increased. I have tested this with some random data.
Stress Testing 1
![123](https://cloud.githubusercontent.com/assets/12194719/17273178/bacc244c-56c9-11e6-9b1a-e8a46c2ee951.png)
Stress Testing 2
![1234](https://cloud.githubusercontent.com/assets/12194719/17273190/016e1f36-56ca-11e6-9522-dadc483c7705.png)

**Comment by aayusharora** [comment]
@mariobehling Solved in #562

**Comment by championswimmer** [comment]
done
