### ISSUE TITLE
Tracks are not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#55]
No clicking possible, no information.
http://fossasia.github.io/open-event-webapp/#/tracks

**Comment by SaptakS** [comment]
I would like to fix this bug. I have seen that it is not possible to click and there is no information either. Where do I get the information to be put there and will an accordion be fine?

**Comment by championswimmer** [comment]
An array of sessions is saved in the $sessionStorage.sessions object. We
need to get sessions from there, and filter then according to the track.

**Comment by SaptakS** [comment]
You mean, when I click a track, I need to show only the sessions corresponding to the track?? Something like that??

**Comment by championswimmer** [comment]
Yes exactly.

note: for later:
Also I want to revisit the way we save the data. Maybe it is not the most
efficient, but yes for now, showing the sessiosn that have the given track
X in it's "tracks" field should be shown when we click on a track

**Comment by SaptakS** [comment]
Ok.. I will send a pull request after I do it. I will ask again if I face any problem.

**Comment by SaptakS** [comment]
I have one more doubt. As I see, the sessions have a title, a type, language and a speaker.. I don't see anything related to tracks. So what exactly do I need to match with the track? Should I add a category all together to the sessions which I can compare with the tracks?

**Comment by leto** [comment]
Howdy,

The API JSON response data for a session should contain some kind of
session identifier which tells the track that the session is a part of. If
not, it should.

Hope that helps,

Duke

On Sat, Sep 12, 2015 at 9:06 PM, Saptak Sengupta <notifications@github.com>
wrote:

> I have one more doubt. As I see, the sessions have a title, a type,
> language and a speaker.. I don't see anything related to tracks. So what
> exactly do I need to match with the track? Should I add a category all
> together to the sessions which I can compare with the tracks?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fossasia/open-event-webapp/issues/55#issuecomment-139843188>
> .
>



-- 
Jonathan "Duke" Leto <duke@leto.net>
Leto Labs LLC http://letolabs.com
209.691.DUKE http://duke.leto.net
@dukeleto http://linkedin.leto.net https://github.com/leto

**Comment by championswimmer** [comment]
http://openevent.championswimmer.in/api/v1/event/1/sessions/page/2

Yeah currently they are all coming out to be null.

I think you this needs be an issue flagged up on
https://github.com/fossasia/open-event-orga-server

**Comment by SaptakS** [comment]
on updating bower and deploying the project, i get this error:
Error: [$injector:modulerr] Failed to instantiate module openevent due to:
[$injector:modulerr] Failed to instantiate module leaflet-directive due to:
[$injector:modulerr] Failed to instantiate module nemLogging due to:
[$injector:nomod] Module 'nemLogging' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.6/$injector/nomod?p0=nemLogging
minErr/<@http://localhost:8080/bower_components/angular/angular.js:68:12
module/<@http://localhost:8080/bower_components/angular/angular.js:1986:1
ensure@http://localhost:8080/bower_components/angular/angular.js:1910:38
module@http://localhost:8080/bower_components/angular/angular.js:1984:1
loadModules/<@http://localhost:8080/bower_components/anugular/angular.js:4388:22
forEach@http://localhost:8080/bower_components/angular/angular.js:336:11
loadModules@http://localhost:8080/bower_components/angular/angular

Can you help me out?

**Comment by SaptakS** [comment]
Fixed the issue. Needed to add angular-simple-logger as a dependency.

**Comment by SaptakS** [comment]
I am facing a problem. Though the above issue has been resolved in the above mentioned repo, but when I deploy my local repo, it still doesn't show any change. 

The values have changed here http://openevent.championswimmer.in/api/v1/event/1/sessions
But when I open the website, it still shows null track. Am I missing something?

**Comment by SaptakS** [comment]
fixed here https://github.com/fossasia/open-event-webapp/pull/75

**Comment by SaptakS** [comment]
I guess this issue is fixed?

**Comment by creativepsyco** [comment]
This has been fixed by @SaptakS.
Cheers!
