### ISSUE TITLE
Pop over info usually off-screen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#570]
Implement solution that shows pop-over info on screen always.

![screenshot from 2016-08-05 17 46 05](https://cloud.githubusercontent.com/assets/1583873/17442371/caf05116-5b35-11e6-8f00-c25a8ed231cf.png)

**Comment by aayusharora** [comment]
@mariobehling **"Implement solution that shows pop-over info on screen always"** 
What does it exactly mean. The popovers behave same as sched.org.
![123](https://cloud.githubusercontent.com/assets/12194719/17456097/63d82e36-5be9-11e6-80ae-b62786245c32.png)
Just need to adjust some left margin here. 
According to the issue It seems we want all info in the window view without scrolling from browser.
That use case is not possible because we don't decide the height of pop-box. It is decided automatically according to data same as sched.org. As we are not using any internal scrollbars.

**Comment by championswimmer** [comment]
@mariobehling do we need to keep this issue open ? 
popups are like sched.org only as @aayusharora has mentioned

**Comment by mariobehling** [comment]
Other testers told me they have the same issue. We need to think about a solution, but apparently there are other issues on the list as well. So we can come back to this afterwards.
