### ISSUE TITLE
Implement a featured speaker section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#573]
Something similar to this one.

![screenshot from 2016-08-05 18 06 10](https://cloud.githubusercontent.com/assets/1583873/17442720/59f1e4d2-5b37-11e6-96a4-dd0a9dc1e662.png)

**Comment by aayusharora** [comment]
@mariobehling @championswimmer This should be on Homepage right and the speakers page should be designed with pop-overs ?

**Comment by mariobehling** [comment]
Pop-over offers more info. Just implement in this style. I would just ask you to stick to the FOSSASIA style of the former events now as the designs have numerous issues so far.

**Comment by championswimmer** [comment]
@aayusharora 

On event main page : 
 - Show speakers which have featured : true 
 - Show bio along with name and organisations (like photo posted by @mariobehling ) 

On speakers page:
 - Show all speakers
 - Show details of bio, sessions etc in popbox (like you have already implemented in front page)

**Comment by aayusharora** [comment]
@championswimmer  Thanks that clears the confusion

**Comment by aayusharora** [comment]
@mariobehling  Please see the snapshot you have given contains all speakers with small descriptions/bio. Hence it looks fine. But when I done this with long descriptions the layout was disturbed.
Test Case 1
![123456](https://cloud.githubusercontent.com/assets/12194719/17465960/3bccc6a2-5d21-11e6-91ac-54356b0dff85.png)
Test Case 2
![12345](https://cloud.githubusercontent.com/assets/12194719/17465964/4f970e2c-5d21-11e6-9ee1-b1fa77e1cf50.png)

Do consider the same thing is happening at Fossasia16 website but not noticed much because the descriptions are not very large.
![1234567](https://cloud.githubusercontent.com/assets/12194719/17465974/820497bc-5d21-11e6-91ae-e52c785dc4f4.png)
Possible solution might be a **Read more** toggle button with fixed height of speaker description.
What's your opinion?

**Comment by mariobehling** [comment]
@aayusharora Yes, looks good, but please limit the number of words to match the height of the image and show the complete text on scroll over.

**Comment by aayusharora** [comment]
This is done #600

**Comment by mariobehling** [comment]
This is not visible in the demo site. I am not sure, if the JSON needs to be adapted, but the start page still shows all speakers.

**Comment by championswimmer** [comment]
done via https://github.com/fossasia/open-event-webapp/pull/679
