### ISSUE TITLE
Autogenerate sample site after each commit in github pages branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#724]
Autogenerate a sample site after each commit in [github pages branch](http://fossasia.github.io/open-event-webapp/) using the current version of the FOSSASIA sample at 
https://github.com/fossasia/open-event/tree/master/sample/FOSSASIA16 .

**Comment by shubham-padia** [comment]
@mariobehling @championswimmer @aayusharora  I would like to work on this,
I've implemented a rough implementation of this feature at this branch [here](https://github.com/shubham-padia/open-event-webapp/tree/auto-gh) . Click [here](https://shubham-padia.github.io/open-event-webapp/) for the auto-generated sample site and its gh-pages branch [here.](https://github.com/shubham-padia/open-event-webapp/tree/gh-pages)

I've been facing two problems so far : 
1) Cannot download images properly ( Images are saved but their size remains 0 when providing api endpoint. ( cannot download them when using the app locally or on travis but works fine on https://opev-webgen-dev.herokuapp.com/ )
2) app gets stuck when it reaches the mailing part due to the lack of sendgrid api key ( on the specified  [branch](https://github.com/shubham-padia/open-event-webapp/tree/auto-gh) , i'm simply exiting the program before it reaches the mailing part )

If the above approach seems okay , please guide me further.

**Comment by aayusharora** [comment]
@shubham-padia I don't know why the image in the end point http://open-event-dev.herokuapp.com/api/v2/events/179/speakers  you are using is https://opevbucketname.s3.amazonaws.com/events/179/speakers/1263/photo/MFhNSk9yRU/HansBakker_111.jpg whose content type seems to be 'binary/octet-stream' instead of image/png. Its orga endpoint issue, Can you please confirm by checking another endpoint.

**Comment by shubham-padia** [comment]
@aayusharora I tried changing the endpoint to http://open-event-dev.herokuapp.com/api/v2/events/171 ,  but as seen [here](https://shubham-padia.github.io/open-event-webapp/) , images are still not being downloaded.

**Comment by shubham-padia** [comment]
@mariobehling @aayusharora 
I've fixed the Content-Type problem in https://github.com/fossasia/open-event-orga-server/pull/2440 and the mailing part is also not an issue now, the site is now being auto-generated successfully at each commit as seen in the demo [here](https://shubham-padia.github.io/open-event-webapp/).

Should I go ahead and generate a PR for the same ?

**Comment by mariobehling** [comment]
@shubham-padia It looks like you are generating an older site. Some changes and features are missing in your site, e.g. search.

**Comment by shubham-padia** [comment]
@mariobehling Was working on a different branch for that, forgot to update it :smiley: , updated it now.
Please check the  [link](https://shubham-padia.github.io/open-event-webapp/) again.
Its gh-pages branch can be seen [here](https://github.com/shubham-padia/open-event-webapp/tree/gh-pages)

**Comment by mariobehling** [comment]
The schedule and tracks page have a problem with the order of sessions, e.g. starting on top with sunday or starting with wrong time.

**Comment by shubham-padia** [comment]
@mariobehling 
Seems that in the webapp the id of sessions is also taken into account when sorting the sessions,  changes in the id of the sessions at the orga-server is causing the problem.

The id for the sessions are changed when the sample zip is imported in the orga-server.
e.g  https://www.diffchecker.com/vnsypfTc.
- Sessions from sample: https://gist.github.com/shubham-padia/243bba827c6eec50fca049bd0ce29ba4
- Sessions after exporting the event from orga server: https://gist.github.com/shubham-padia/243bba827c6eec50fca049bd0ce29ba4

Don't know if i am missing something here or is this a webapp/orga-server issue?

**Comment by mariobehling** [comment]
@shubham-padia Are the issues still there? Would be great to get the autogenerate feature. Are you still interested in it? Should I assign you?

**Comment by shubham-padia** [comment]
@mariobehling Been busy with some college work for quite some time. Yes , please assign it to me. Would start working on it in a day or two.
