### ISSUE TITLE
add feature to generate from command line (without the frontend webpage) 

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#727]
this would be needed for automated deployments like https://github.com/fossasia/open-event-webapp/issues/724

**Comment by Abhi2424shek** [comment]
I got an idea, can I work on it @championswimmer. Sending a post request from cmd with the required files as parameters could help right!

**Comment by championswimmer** [comment]
No I would prefer you write a cli.js file that requires generator.js and runs the functions. Why make a http-server when not needed.

**Comment by championswimmer** [comment]
You can work on the issue if you wish to :)

**Comment by shubham-padia** [comment]
@championswimmer I'm thinking of a different approach , which would create a `cli.js` with a socket.io-client instance and accept an open-event api endpoint , i've implemented  a `cli.js` for that [here](https://github.com/shubham-padia/open-event-webapp/blob/7e0d052c39dece8a5b0f0b6c7a524651985e017d/cli.js) which works fine in my travis and local setup till the mailing step due to the lack of sendgrid api key, is there a way to skip this step ?

**Comment by Abhi2424shek** [comment]
@championswimmer the thing I mentioned is something cool, its simple and easy plus secure all you want to do is that what the browser does for you on the click of a button

**Comment by shubham-padia** [comment]
@mariobehling Please update the issue . Looks like this issue can be closed .
