### ISSUE TITLE
Share button links to wrong domain

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#731]
* [ ] The share button should always link to the respective domain location, but it is hard-coded to "opentechsummit.net".
* [ ] Share buttons should be available at all areas - sessions in tracks, schedule, rooms - and to speakers

![screenshot from 2016-08-29 12 41 41](https://cloud.githubusercontent.com/assets/1583873/18049088/5332f53e-6de6-11e6-82de-ab0c750cbf8a.png)

![screenshot from 2016-08-29 12 42 19](https://cloud.githubusercontent.com/assets/1583873/18049091/56c96ee4-6de6-11e6-82c6-399e94ff7d1d.png)

**Comment by championswimmer** [comment]
@mariobehling there is a problem here. How do we know where the user will host it ? the link will change based on which location it is hosted at
ok, i think we can use window.location then. that should work
Mario Behling
@mariobehling
16:28
@arnav why can't we just link within the folder structure?
e.g. ./tracks.html/#3
Arnav Gupta
@championswimmer
16:36
@mariobehling internal links cannot be shared
we want to share to external service right ? (like on messenger, email, whatsapp or anything)
internal links cannot work if you share externally
Mario Behling
@mariobehling
16:37
wouldn't the links work once the service is deployed?
Arnav Gupta
@championswimmer
16:37
It worked with OTS and FOSSASIA because we knew exactly which folder the programm/schedule is
Yes it'll work. But I do not know which URL it'll be deployed it. Will it be deployed to opev-webgen-dev ? Or we'll get a new domain or something ?
What if user downloads zip, and deploys himself somewhere else ?
So I am thinking we can do with using window.location (in javascript that returns current location of browser url)

**Comment by championswimmer** [comment]
@mariobehling there is a problem here. How do we know where the user will host it ? the link will change based on which location it is hosted at
ok, i think we can use window.location then. that should work
Mario Behling
@mariobehling
16:28
@arnav why can't we just link within the folder structure?
e.g. ./tracks.html/#3
Arnav Gupta
@championswimmer
16:36
@mariobehling internal links cannot be shared
we want to share to external service right ? (like on messenger, email, whatsapp or anything)
internal links cannot work if you share externally
Mario Behling
@mariobehling
16:37
wouldn't the links work once the service is deployed?
Arnav Gupta
@championswimmer
16:37
It worked with OTS and FOSSASIA because we knew exactly which folder the programm/schedule is
Yes it'll work. But I do not know which URL it'll be deployed it. Will it be deployed to opev-webgen-dev ? Or we'll get a new domain or something ?
What if user downloads zip, and deploys himself somewhere else ?
So I am thinking we can do with using window.location (in javascript that returns current location of browser url)

**Comment by championswimmer** [comment]
ok implemented what we discussed. it is working on http://opev-webgen-dev.herokuapp.com now. so closing this

**Comment by championswimmer** [comment]
on heroku 
![screenshot from 2016-08-29 19-55-07](https://cloud.githubusercontent.com/assets/1327050/18055025/f1110060-6e23-11e6-8733-f26d92c75ef8.png)

on ghpages
![screenshot from 2016-08-29 20-05-06](https://cloud.githubusercontent.com/assets/1327050/18055026/f1139384-6e23-11e6-8e12-f8c02c6dbfc0.png)
