### ISSUE TITLE
Implement two image versions for speakers and sponsors: Icon and Thumbnail

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#770]
The orga server already offers two image sizes a) Icon and b) Thumbnail.

We also need two versions in the web app site.

We also need two versions in the web app site for the different areas.

In order to achieve this we could implement/add the different files sizes into the sample file. Alternatively we can scale the image sizes in the generator, which might be the more suitable for the time being in order not to clutter the file format too much.

**Comment by shubham-padia** [comment]
@mariobehling I would like to work on this. Thumbnails for speaker images are only required in the currrent implementation, which we can store in `/images/thumbnails/speakers` and i plan to use https://github.com/lovell/sharp for resizing the images.

**Comment by mariobehling** [comment]
Thank you.

Two questions: 

1. /images/thumbnails/speakers or maybe better /images/speakers/thumbnails ?

2. Could we include https://github.com/lovell/sharp as a submodule in Github?

**Comment by shubham-padia** [comment]
@mariobehling 
1. Yes, that can be done. Although i have impemented `/images/thumbnails/speakers` on https://shubham-padia.github.io/open-event-webapp ( in the tracks,rooms and schedule pages ), i will start making changes shortly to stick to the format of `/images/speakers/thumbnails`
2. `sharp` can be added as an npm dependency and no external libraries are required for it, so that's not an issue.
