### ISSUE TITLE
Venue page: Add more info details

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#780]
On venue page, e.g. in the sample http://fossasia.github.io/open-event-webapp/rooms.html show more information 

On a second line below the session title show information in smaller font as follows:
- [x] Picture of speaker
- [ ] Name of speaker
- [x] In brackets: organization/project
- [x] Type of session
- [x] Link icon that shows link on click ![screenshot from 2016-09-05 19 32 18](https://cloud.githubusercontent.com/assets/1583873/18262985/b9cd6a88-7406-11e6-8f0f-369b2486b344.png) (see current tracks page)

![screenshot from 2016-09-05 19 35 14](https://cloud.githubusercontent.com/assets/1583873/18254662/262f6e7c-73a0-11e6-8711-549c6442a270.png)

**Comment by Princu7** [comment]
I would like to work on this issue. Also can you please clarify your last point? Does link icon refers to icons of github, twitter and linkedIn?

**Comment by mariobehling** [comment]
Thank you. With link icon I mean the functionality that is on the current tracks page: [screenshot from 2016-09-05 19 32 18](https://cloud.githubusercontent.com/assets/1583873/18262985/b9cd6a88-7406-11e6-8f0f-369b2486b344.png) (see current tracks page)

**Comment by Princu7** [comment]
@mariobehling I am having a hard time figuring out a way to include the type of session. It's a bit difficult to describe the problem but I'll give it a try.
On the rooms page, the sessions are categorized according to the date and the venue of the event.Now the object which contains the date and the list of sessions on that day along with their venue doesn't include the type of the sessions. The type of session is included in another object but that object contains the sessions categorized according to the date and the title. Not according to the venue as we want in our rooms page.This other object is used in the tracks page and we can't directly use it here in our rooms page. 

I have some solutions in mind to solve this problem. But first I would like to be certain whether what I am thinking is actually correct or not.

Here is how the rooms page looks so far without the type of session and the link functionality.

![screenshot from 2016-09-11 13-34-21](https://cloud.githubusercontent.com/assets/8847265/18416021/9a2e4a22-7824-11e6-8a49-0eeb52203076.png)

**Comment by Princu7** [comment]
Ok. The work is almost done now. Here is how it looks.
![screenshot from 2016-09-13 11-44-02](https://cloud.githubusercontent.com/assets/8847265/18463450/e414df96-79a7-11e6-8b1b-e5f2f59dc1f9.png)
![screenshot from 2016-09-13 11-44-19](https://cloud.githubusercontent.com/assets/8847265/18463454/ebd48790-79a7-11e6-96bd-10a57037c6af.png)
VIews?

**Comment by mariobehling** [comment]
Can we try it out somewhere? Could you set it up on your own repo as gh-pages, please?

**Comment by Princu7** [comment]
@mariobehling I have not worked with github pages before so apologies in case of some mistake.
Anyways, Take a look at the page here
https://princu7.github.io/websiteTest/rooms.html

**Comment by mariobehling** [comment]
Ok, thank you. Looks good. Two questions:
* [ ] Any way to reduce the height and keep the look and feel good.
* [ ] The expansion effect on my browsers is a bit slow. Any way to make it fast?

**Comment by Princu7** [comment]
@mariobehling Thanks. 
1. I tried experimenting with the height of the container but reducing it only seemed to clutter up the contents and make it look less tidy. The current display format of session title followed by the picture of speaker and his/her information doesn't really allow us for a shorter height variant of the container which will keep the neat and tidy look. All what I can think of right now is to reduce padding by 5px which will reduce the height of the container by 10px. The look will almost be the same accompanied by a slight decrease in height.

2. I compared the expansion time of both the original implementation and the current implementation in my browser. The original is just a tiny bit faster than the current  and that's because in the current version one div is expanding while the other div is contracting simultaneously causing a momentary delay. I used the same bootstrap class which was used in the original implementation. So it's quite difficult to optimize it even further.

**Comment by mariobehling** [comment]
Ok, thanks. Please make a PR and we try to go from there. Let's ask others for ideas to speed up the effects. Cheers.

**Comment by aayusharora** [comment]
@Princu7 What's the status for this issue ?

**Comment by Princu7** [comment]
@aayusharora The first four points have been implemented and tested successfully. I am having some problem in solving the fifth point. Need some guidance on how to incorporate the link icon that shows the link on click from the tracks page to. I tried to copy the same code on the rooms page but it didn't work the way I expected it to be.

**Comment by jainaman224** [comment]
@Princu7 I would like to implement fifth point.

**Comment by mariobehling** [comment]
@jainaman224 Please go ahead. Thank you.

@Princu7 The text is not aligned currently. Any idea about this?

![screenshot from 2016-10-05 09 54 38](https://cloud.githubusercontent.com/assets/1583873/19105379/ee580320-8ae1-11e6-9fe0-6e8e2233a35b.png)

**Comment by Princu7** [comment]
@jainaman224 Thanks. I have fully implemented the above four points. I am sorry but I am not sure how to collaborate on the fifth point. Should I send in my request and then you will implement the fifth point or we send it at once?  Again, I apologize for not being familiar with the process.
@mariobehling  If you are talking about the mismatch of the session title bar with the text below, it is arising because of the left margin of the session title bar.
How does this look?
![screenshot from 2016-10-05 17-26-36](https://cloud.githubusercontent.com/assets/8847265/19112160/031925e8-8b21-11e6-9c87-13b8d8295614.png)
If this is not what you intended to say, then apologies on my part. Please specify the issue again. Thanks for suggesting the improvement.

**Comment by mariobehling** [comment]
@Princu7 Thanks. Yes, this is how it should look like. Cheers.

**Comment by jainaman224** [comment]
@Princu7 Sure I will merge both PR. :+1:

**Comment by Princu7** [comment]
@jainaman224  I am sorry but I didn't got what you are saying :smile: . Sorry for not understanding.  I will send a pull request containing the 4 points that I implemented and the recent change that the Mario sir suggested as soon as I can. Please work from that point.  I hope it is okay.

**Comment by jainaman224** [comment]
@mariobehling Can you please review for fifth point https://jainaman224.github.io/open-event-webapp/issue780/rooms.html...?
I will add it later with @Princu7 modifications.

**Comment by mariobehling** [comment]
@jainaman224 Thank you. Please move the icon to the links/social media line.

![screenshot from 2016-10-12 05 59 42](https://cloud.githubusercontent.com/assets/1583873/19297011/18baa47e-9041-11e6-99a9-6a444476d959.png)

**Comment by jainaman224** [comment]
Will it be beneficial to make input box with link to be read only to avoid modification by the user...?
