### ISSUE TITLE
Propose and implement way to generate smaller html files and offline caching mechanisms

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#781]
If the schedule is large the app generates relatively large html files, that can be larger than 1MB. Please propose and implement more efficient html file implementations and efficient caching mechanisms of the site.

**Comment by mbad0la** [comment]
@mariobehling if I may put my opinions.

Currently the website is being rendered by a template, which is directly fed the data through a relevant source. In such a case, the **current implementation** (which is static) **will grow proportional** to the the **schedule** size no matter what.

From what I know, you might have to ingest your json data into a database and program scripts to retrieve them - taking away some of the automation from this project, due to an increase in operational overhead.

**Comment by alexagr** [comment]
FWIW simply enabling compression in Web server settings reduces the size of transferred data by almost 90%, bringing size of, for example, rooms.html from 1.6 MB to 229 KB.

**Comment by mariobehling** [comment]
@alexagr Let's suppose we use github pages. Any suggestions for this case?

**Comment by alexagr** [comment]
@mariobehling GZIP compression is automatically enabled on GitHub pages

**Comment by shubham-padia** [comment]
@mariobehling Can you please update the status on this issue ?
