### ISSUE TITLE
Speakers Page: Generate several web icon links if they are in the speakers profile

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#784]
Currently the web app generates links to social media and websites. In the specification of the JSON format it is possible, that there are several websites, twitter accounts etc. specified, but the web app generator only generates one link.

Please
- [ ] Show several icons of an item if there are several links, e.g. there can be two website links in the speakers profile and therefore there should be two web link icons with links. An example is Anh Tuan Truong who has two links.

**Comment by aayusharora** [comment]
@mariobehling @championswimmer I was just going through the current JSON and find out the keys are not unique. Two website keys should not be there, Instead of this a website Array makes more sense and is more correct according to me.

![yu](https://cloud.githubusercontent.com/assets/12194719/18323587/e0c7eeec-7555-11e6-84b7-81baacee4975.png)

**Comment by karanagarwal17** [comment]
I would like to work on this issue.

**Comment by agbilotia1998** [comment]
@aayusharora @mariobehling is this issue still there , I guess in the above provided link there are no multiple website keys now for the speaker.
