### ISSUE TITLE
Make Line-Width Less on Hover ( Mobile Screen)

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#786]
When Menu items are hovered on Small Screens or Tablets, the line width looks bad. 
Please decrease the line width, say below Tracks in snapshot
![7](https://cloud.githubusercontent.com/assets/12194719/18324361/bb4e76be-7559-11e6-9109-e4f371dbd325.png)

**Comment by poush** [comment]
I would like to work on this. Also I suggest for mobile version all borders should be visible not just bottom because they are visible only when these links are clicked. May be like this
<img width="509" alt="screen shot 2016-10-10 at 11 30 52 am 1" src="https://cloud.githubusercontent.com/assets/1812082/19227892/1cafb2e6-8edd-11e6-9c1c-4d06f98df679.png">

and border bottom only will look like this
<img width="457" alt="screen shot 2016-10-10 at 11 32 34 am" src="https://cloud.githubusercontent.com/assets/1812082/19227918/57a55496-8edd-11e6-9df7-3f6117664121.png">

**Comment by mariobehling** [comment]
@poush @aayusharora Yes, for the mobile version could we go with something bigger instead of the underline? Actually, before we had a gray background for this feature, but it is not there somehow.

It would be great to get the gray background back again.
