### ISSUE TITLE
Suggest best way to Implement HTML rendering

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#798]
{{{....}}} can lead to XSS vulnerabilities but using this {{..}} instead of {{{..}}} will not allow HTML to render on the page.
Reverting  #788 is not the only solution. These {{{...}}} are used for escaping everywhere in the code when we want to render HTML from JSON. 
Please implement a solution for the replacement of {{{...}}}.

One option I can suggest is using https://github.com/yahoo/secure-handlebars

**Comment by aayusharora** [comment]
@shubham-padia What's your views?

**Comment by shubham-padia** [comment]
- https://github.com/yahoo/secure-handlebars sounds like a good solution as it is made for handlebars specifically.
- If you want  to specify the tags you want to permit, and the permitted attributes for each of those tags https://github.com/punkave/sanitize-html can also be used. So if we do not want the user placing an img tag in a textual description, this module can be more useful.

So. if we want to allow user to enter harmless html tags , https://github.com/yahoo/secure-handlebars would work fine and https://github.com/punkave/sanitize-html would be fine if we want to allow only certain html tags.

@aayusharora What do you think ?

**Comment by Princu7** [comment]
Sorry for being off the radar for some time. I agree with the opinion to use secure-handlebars.  Most of the html tag will be for specifying the link of some website as seen in the json so using sanitize html won't be too bad of a option either.

**Comment by mbad0la** [comment]
@aayusharora @shubham-padia @Princu7 if the website is generated through a json file and as such there isn't any user input into the generated webapp, I don't follow how the website is XSS vulnerable. 

There has to be some form of client-side code injection into the webapp for the app to be vulnerable. Am I missing something?

**Comment by Princu7** [comment]
I might be wrong but JSON file itself is given by the user who wants to generate the event website.

**Comment by aayusharora** [comment]
@mbad0la @Princu7  Yes the user provides the JSON itself

**Comment by mbad0la** [comment]
@Princu7 @aayusharora as the only input that goes into the app is of the person who provides the data for the generation of **his** app, shouldn't he be completely familiar with the "malicious code" that might get generated onto the website?
I think this is something which we shouldn't worry about because having an XSS vulnerable site and creating a malicious site (which doesn't even hold here because nothing, after what was fed at the generation stage, gets injected into the app) are two different things.
Opinions?

**Comment by shubham-padia** [comment]
@mbad0la Although the person will be providing the data for generation of his own app, consider an example where the event organiser without any technical knowledge is collecting data from each of the speaker, and one of the speaker tries to have some fun and injects some js code into the json. Well in this case the organiser will just think the generator has some fault in it and switch to some other option.

And second point , as far as i know when using the generator the website files generated by the user are stored for a limited time on the generator server, and if the user  provides a malicious json, then he may even find a way to meddle with the generator server itself.

@mbad0la @aayusharora @Princu7 Your views?

**Comment by mbad0la** [comment]
@shubham-padia I completely agree with your first point, but it would be tough (or near impossible) to identify what qualifies as malicious code during generation. ( It might be possible that some of the **\<script\>** tags refer to some malicious code and some may not )

Although, I'm quite certain that the generated files won't be able to meddle with the server as they are just generated and never executed on the server. The only instance of their execution is through a browser which then in turn won't be able to harm any server as the scripts would be executed through a browser JavaScript engine rather than the Node intepreter on the server.

**Comment by shubham-padia** [comment]
@mbad0la My bad, I got the second part wrong. 

For the first point though, as long as the user is not denied the basic html tags, there seems no harm in ensuring that the generated site provided to the user is free from known potential xss vulnerabilities.
Also , i see no point in allowing user to enter script tags in his description or any other such fields.
If the user wishes to do so, he may as well do it after the downloading the site.

**Comment by Princu7** [comment]
@aayusharora  @shubham-padia  @mbad0la  Your arguments are excellent. I definitely agree about the script part. I think users should only be allowed to enter some basic html tags like <a> or <ul>. There is no need of allowing any javascript lines into them. 
Also I was going through the different template files and I could still see some variables which were unescaped. What do we do now for them? Should I correct them and send in a request or wait for a while?

**Comment by aayusharora** [comment]
@mariobehling @championswimmer  Whats your suggestion about this ?
