### ISSUE TITLE
UI Bugs - sidebar line and scroll feature on clicking dates

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#866]
* [x] Ensure left sidebar line is going through without breaks on rooms and tracks page

![screenshot from 2016-10-18 23 45 11](https://cloud.githubusercontent.com/assets/1583873/19497553/21010ed8-958d-11e6-9cc3-7811e8c31d7a.png)

* [x] On tracks and rooms page ensure dates clicked use the scroll feature, e.g. test Friday and Sunday on sample site http://fossasia.github.io/open-event-webapp/tracks.html

**Comment by Princu7** [comment]
I can work on this one.
Regarding first point, does this look good? @mariobehling 
![screenshot from 2016-10-19 14-17-47](https://cloud.githubusercontent.com/assets/8847265/19511929/30ee4d68-9607-11e6-8b92-5a73bf4fa036.png)

**Comment by Princu7** [comment]
@mariobehling  I have completed the work. The second bug was quite nasty and took quite some time to find. The problem was we were using the _slug_ of a track as an _ID_ but the slug can sometimes consist of multiple words consisting of spaces which isn't the usual norm for naming an _ID_.Anyways I made some changes in the scroll.js file and it is working fine now. You can test it here.

https://princu7.github.io/websiteTest/
Please review. Thanks!!

**Comment by shubham-padia** [comment]
@mariobehling Looks like this issue can be closed. Please update the issue. Thank You.
