### ISSUE TITLE
Poor documentation of deploying Open Event Web App on Google Cloud

### ISSUE THREAD

**Issue by aryanbhasin** [fossasia/open-event-webapp#922]
The current documentation is at:
https://github.com/fossasia/open-event-webapp/blob/development/docs/INSTALLATION_GOOGLE.md

This documentation does not refer to using Google Cloud Console to manage projects.
It does not give clear instructions of setting up instances, and does not make any reference to deploying the app on Google Cloud's App Engine flexible environment.
Additionally, the instructions given currently are applicable for deployment on a local host, instead of Google Cloud.
I would like to improve this documentation

**Comment by mariobehling** [comment]
Thanks for working and solving this issue. I would like to ask you to keep your language more positive and encouraging in future please, especially in issues. E.g. instead of saying "poor documentation" it could be "Improve documentation". This might help to get issues solved faster, if you need help in the future. Cheers. ;-)
