### ISSUE TITLE
Performance: Scale Speakers and Sponsor images before CSSOM generation

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#960]
- While generating images in a folder from user's uploaded zip, the images are directly generated or fetched from API in the folder.

## Proposed solution
- We already know the size of each sponsor image `max-height: 80px;
    max-width: 150px;` which can be scaled before CSSOM generation.
## Help Link  
https://www.npmjs.com/package/node-image-resize

**Comment by adarsh-ideal** [comment]
@aayusharora I would like to work on this.

**Comment by poush** [comment]
I am working on this. First tried using "sharp" module with sponsor images, it is working but the only issue is that it is cropping the images instead of resizing in resolution. 
Here is the commit https://github.com/poush/open-event-webapp/commit/bc8720ab32264a6fed261a62363c32a2f26f7ff1 of it.

About that module "node-image"resize", it is not updated since 3 years supporting old version of nodejs. 

I will look into it more tonight.
